env:
  node: true
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
globals:
  console: true
  google: true
  initMap: true
  pubs: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - never
  no-console:
    - error
    - allow:
      - info
      - warn
      - error
